databases:
  - name: business-erp-db
    databaseName: businesserpdb
    user: businesserpuser
    plan: free

services:
  - type: web
    name: business-erp-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_JWT_SECRET
        value: 9a2f8c7e1d4b6a3f5e0c8b7a6d5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c
      - key: DB_HOST
        fromDatabase:
          name: business-erp-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: business-erp-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: business-erp-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: business-erp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: business-erp-db
          property: password
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_USERNAME
        value: tejupay@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: dsmhydrmmxvypzad

  - type: web
    name: business-erp-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: VITE_API_URL
        value: https://business-erp-backend.onrender.com

